### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by McLovin-81** [McLovin-81/littleGroupData#4]
Implement that the proxy should be only used if the connection didn't work

**Comment by mehr74** [comment]
One way to do this is through using environment variables. We can set the proxy to http_proxy or https_proxy. The solution assumes that the operating system running the code has already set up proxy. 
The other solution would be to use arguments and pass proxy as an argument to the program.
https://github.com/McLovin-81/littleGroupData/pull/5

**Comment by McLovin-81** [comment]
Thx bro!
